### ISSUE TITLE
Make bingo field responsive to view size

### ISSUE THREAD

**Issue by Serveny** [Traijan1/bingo#1]
To include the bingo field into a browser source in OBS, it would be better if the field was responsive to the given window size.

**Comment by Traijan1** [comment]
This would be a great feature.

I think the best solution is to have a "streamer mode", which you can enable with a query or similiar.
Maybe something like: *url*/bingo/*id*?streamer=true

I am also rethinking about the 100x100px per field restriction. It's bad for mobile but I don't want that it can expand to full size for the user that wants to click on it. 

I will think about a nice and clean solution.
